version: '3'
services:
  api:
    image: wandersouza/smite-match-tracker-ebs:1.0.0
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - NODE_ENV=${NODE_ENV}
    env_file:
      - ./.env
networks:
  default:
    name: nginx-proxy
    external: true
